Repository roniemartinez/latex2mathml, pull requests merged in 2023-05, with the labels that each got.

#393 🐛 Fix spaces in \begin, \end and \operatorname
  latex2mathml/tokenizer.py
  pyproject.toml
  tests/test_tokenizer.py
Labels: fix

#395 🐛 Fix prime combined with subscripts or superscripts
  latex2mathml/walker.py
  pyproject.toml
  tests/test_walker.py
Labels: fix

#396 📚 Fix badge
  README.md
Labels: documentation

#400 pep396
  latex2mathml/__init__.py
Labels: enhancement
